apiVersion: v1
kind: Pod
metadata:
    name: explore-billy
spec:
    containers:
    -   name: vol-ct
        image: jmduarte/hbb_interaction_network
        args: ["sleep", "36500000"]
        volumeMounts:
        -   mountPath: /cookiecutter-bench
            name: cookiecutter-bench

        resources:
          limits:
            memory: 12Gi
            cpu: "2"
          requests:
            memory: 12Gi
            cpu: "2"
    restartPolicy: Never
    volumes:
        - name: cookiecutter-bench
          persistentVolumeClaim:
            claimName: cookiecutter-bench        
