apiVersion: v1
kind: Pod
metadata:
    name: hbb-data-download
spec:
    containers:
    -   name: vol-ct
        image: jmduarte/capstone-particle-physics-domain
        command:
          - "/bin/bash"
          - "-c"
          - >
            cd /cookiecutter-bench &&
            rm -rf hbb_interaction_network > /dev/null &&
            git clone https://github.com/FAIR4HEP/hbb_interaction_network.git &&
            cd hbb_interaction_network &&
            git checkout add_code &&
            pip install --user -r requirements.txt &&
            cd src/data &&
            python3 download_raw.py
        volumeMounts:
        -   mountPath: /cookiecutter-bench
            name: cookiecutter-bench
    restartPolicy: Never
    volumes:
        - name: cookiecutter-bench
          persistentVolumeClaim:
            claimName: cookiecutter-bench 
