apiVersion: v1
kind: Pod
metadata:
    name: hbb-train
spec:
    containers:
    -   name: vol-ct
        image: jmduarte/hbb_interaction_network
        command:
          - "/bin/bash"
          - "-c"
          - >
            cd /cookiecutter-bench/hbb_interaction_network &&
            git pull &&
            git checkout process_data &&
            pip3 install --user -r requirements.txt &&
            pip3 uninstall -y torch torchvision torchaudio &&
            pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116 &&
            cd src/models &&
            python3 train_model.py
        volumeMounts:
        -   mountPath: /cookiecutter-bench
            name: cookiecutter-bench
        resources:
          limits:
            memory: 12Gi
            cpu: "2"
            nvidia.com/gpu: "1"
          requests:
            memory: 12Gi
            cpu: "2"
            nvidia.com/gpu: "1"
    restartPolicy: Never
    volumes:
        - name: cookiecutter-bench
          persistentVolumeClaim:
            claimName: cookiecutter-bench 
