apiVersion: batch/v1
kind: Job
metadata:
    name: hbb-train-gpu-1024
spec:
    template:
        spec:
            containers:
            -   name: vol-ct
                image: jmduarte/hbb_interaction_network:gpu
                command:
                  - "/bin/bash"
                  - "-c"
                  - >
                    PATH=$PATH:/cookiecutter-bench/cuda_related/bin &&
                    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cookiecutter-bench/cuda_related/lib64 &&
                    cd /cookiecutter-bench/hbb_interaction_network &&
                    git pull &&
                    git checkout main &&
                    pip install -e . &&
                    python src/models/train_model.py --batch-size 1024 --epoch 100 --device cuda
                volumeMounts:
                -   mountPath: /cookiecutter-bench
                    name: cookiecutter-bench
                resources:
                  limits:
                    memory: 12Gi
                    cpu: "2"
                    nvidia.com/gpu: "1"
                  requests:
                    memory: 12Gi
                    cpu: "2"
                    nvidia.com/gpu: "1"
            restartPolicy: Never
            volumes:
                - name: cookiecutter-bench
                  persistentVolumeClaim:
                    claimName: cookiecutter-bench 
