apiVersion: v1
kind: Pod
metadata:
    name: hbb-train-cpu
spec:
    containers:
    -   name: vol-ct
        image: jmduarte/hbb_interaction_network
        command:
          - "/bin/bash"
          - "-c"
          - >
            cd /cookiecutter-bench/hbb_interaction_network &&
            git pull &&
            git checkout cpu &&
            pip install --user -r requirements.txt &&
            cd src/models &&
            python3 train_model.py
        volumeMounts:
        -   mountPath: /cookiecutter-bench
            name: cookiecutter-bench
        resources:
          limits:
            memory: 12Gi
            cpu: "2"
          requests:
            memory: 12Gi
            cpu: "2"
    restartPolicy: Never
    volumes:
        - name: cookiecutter-bench
          persistentVolumeClaim:
            claimName: cookiecutter-bench 
