apiVersion: v1
kind: Pod
metadata:
    name: hbb_data_download
spec:
    containers:
    -   name: vol-ct
        image: ubuntu
        args: ["sleep", "36500000"]
        volumeMounts:
        -   mountPath: /cookiecutter-bench
            name: cookiecutter-bench
    restartPolicy: Never
    volumes:
        - name: cookiecutter-bench
          persistentVolumeClaim:
            claimName: cookiecutter-bench 
